---
title: Permissions and ownership
format:
  html: 
    toc: true
    number-sections: true
    code-fold: true
    embed-resources: true
---

# File and directory permissions

Managing files and directories is only part of working with linux. Another essential aspect is permissions and ownership. These define who can read, modify or execute files and directories. Also play a critical role in keeping your system secure.

You will learn how to change these permissions with the chmod command, manage file ownership with chown and chgrp. Also how to use sudo to temporarily elevate privileges for administrative tasks.

I Linux, every file and directory has a set of permissions that determine who can read, write or execute them. These permissions are essential for keeping your system secure, ensuring that only authorized users can interact with your files.

Permissions are represented in 2 formats:

- **Symbolic format**, using letters like `rwx` (read, write, execute)
- **Numeric format**, based on the values 4, 2 and 1

Lets start by breaking down the symbolic `rwx` format

## The `rwx` notation

- **r (read)**: For files, this allows the contents to be viewed. For directories, it lets users list the files inside
- **w (write)**: For files, this allows changes to be made. For directories, it lets users create, delete or rename files withing the directory.
- **x (execute)**: For files, this allows the file to be run as a program or script. For directories, it lers users enter the directory (`cd`) and access its contents.

## User, group and others

Linux classifies file accesss into 3 categories to control who can interact with a file or directory:

- **User (u)**: the owner of the file
- **Group (u)**: A group of users who share access
- **Others (o)**: Everyone else on the system who is not the owner and not in the group

Whe you run the `ls -l` command

```
ls -l /usr/local/bin/uv
-rwxr-xr-x. 1 root root 54537024 Jan 29 15:02 /usr/local/bin/uv
```

You see a string like `-rwxr-xr-x.` at the start of the line. This string shows not just the file's permission, but also its type, owner, group and other attributes:

- File type character:

  - `-` regular file
  - `d` directory
  - `l` symbolic link
  - `b` block device
  - `c` character device
  - `p` name pipe
  - `s` socket

- Permission meanings

  - r: read (view contents)
  - w: write (modify contents)
  - x: execute (run as a program)

- Security suffix (Alternate access method indicator)

  - ` `: only standard unix permissions apply. No hidden rules. When the character following the file mode bits is a space, there is no alternate access method.  When it is a printing character, then there is such a method.
  - `.`: SELinux Dot so the file has a SELinux security context but no ACLs. GNU ‘ls’ uses a ‘.’ character to indicate a file with a security context, but no other alternate access method.
  - `+`: ACL Plus so the file has a Access Control List (ACL) where it might also have SELinux. A file with any other combination of alternate access methods is marked with a ‘+’ character.  

**Note**: Check `info coreutils 'ls invocation'` and the section **What information is listed** 

So lets brake it in the case of `-rwxr-xr-x.`. This means that `/usr/local/bin/uv` is a regular file because of `-`. The next nine characters are grouped into 3 sets, each showing permissions for a different user category:

- **User (owner)**: `rwx` show that the owner can read, write and execute
- **Group**: `r-x` show that the group can read, not write and execute
- **Others**: `r-x` show that others can read, not write and execute

Next we have `root root`. The first `root` refers to the owner of the file and the second `root` refers to the group that owns the file. Linux allows to assing both a user and a group to each file. In this case both the owener and the group are `root`

Finally we have `.` so the file has a SELinux security context.

Once you understand what these symbols mean, you can quickly tell who owns a file and what they are allowed to do with it, a crucial part of keeping your system under control and secure.

## Numeric format for permissions

Linux permissions can also be represented using a numeric system. More specifically and **octal** (base-8) system.

Each type of permission is assigned a value:

- 4: read (r)
- 2: write (w)
- 1: execute (x)

Add the values together to set the appropiate permissions for each category: user, group and others. For example:

- 7 (4 + 2 + 1): read, write and execute `rwx`
- 5 (4 + 1): read and execute `r-x`
- 4: read only `r--`

**Note**: See page 111 and 112 for a table with the most common permissions.

::: {.callout-tip}
There is no hard rule about whether to use symbolic (`rwx`) or numeric (`755`) format when setting permissions.

Both are valid and widely used, so feel free to choose whichever makes more sense to you.
:::

## Default permissions and umask

When you create a new file or directory in Linux, it is assigned default permissions automatically. These defaults are controlled by a system setting called `umask`.

The umask (user file-creation mode mask) determines shich permission bits should be turned off by default. It substract permissions from the full set (usually `666` for files and `777` for directories)

- For directories the base is `777` (`rwxrwxrwx`). It starts with execute (`x`) because you need that to enter a folder.
- For files the base is `666` (`rw-rw-rw`). It starts without execute (`x`) for safety

This means new file will have permissions of `664` (`666 - 002`) so the mask blocks write permission for `others` (`rw-rw-r--`) and new directories will have permissions of `775` (`777 - 002`) so the mask blocks permissions for `others` (`rwxrwxr-x`)

# Chaing permissions

The `chmod` command it the tool you will use to change the permissions of files and directories. Whether you are using the symbolic `rwx` fromat or the numeric `(4, 2, 1)` format.

## Using the symbolic format with chmod

The basic structure of the `chmod` command is:

```
chmod [who][operation][permissions] filename
```

Where:

- **who**: specifies the user category: `u` for user (owner), `g` for group, `o` for others and `a` for all (user, group and others)
- **operation**: use `+` to add a permission, `-` to remove a permission and `=` to set a permission explicitely
- **permissions**: use `r`, `w` and `x` for read, write and execute.

For example:

```bash
ls -l scripts.sh
-rw-rw-r-- 1 traw traw 0 Jan 11 19:45 scripts.sh
```
To give the owner (user) permission to execute the file, then:

```bash
chmod u+x scripts.sh
```

You can also combine multiple changes in a single command. For example:

```bash
chmod u+x, g+x scripts.sh
```
In that way you give the owner (user) and the group the permission to execute. Also you can use `a+x` to achive `u+x, g+x` and `o+x`. You will often see `chmod +x <filename>` instead of `chmod a+x <filename>`. Both do the same thing.

## Setting permissions explicitely

Instead of adding or removing permissions, you explicitely define which permissions should be active. For example if a file currently has read and write permissions `(rw-)` for the owner, and you want to change it to only have execute permission, you can use `=` to set the permission explicitely:

```bash
chmod u=x <filename>
```

This command would remove the existing read and write permissions and leave the owner with just execute permission (`--x`).

This command ensures that the user (owner) has only execute permission `--x`, regardless of whether they had other permissions (like write or execute) before.

In contrast, using `+` or `-` adds or removes permissions without affecting the others that are already set.

The `=` option ensures that only the specified permissions remain, which is it's called setting permissions explicitely.

## Using the numeric format with chmod

Alternatively, you can use the numeric format we discussed earlier. Each set of permissions (user, group and others) is represented by a number (4 for read, 2 for write and 1 for execute). You can add these number together to set specific permissions.

For example to five the owner full permissions (`rwx`), the group read and execute permissions (`r-x`) and others read only access (`r--`) you would run:

```bash
chmod 754 <filename>
```

This command sets the permissions as:

- Owner: read, write, execute (7)
- Group: read, execute (5)
- Others: read only (4)

### Changing directory permissions

Directory permissions in Linux behave slightly differently from file permissions because they control how users interact with the contents of a directory itself, whether they can enter the directory, list its contents, or modify files inside it.

#### The behavior of Permissions on Directories

- **r (read)**: The `r` permission allows users to list the contents of a directory. However, this doesn't mean they can access or open the files inside it, just they can see the names of files and subdirectories

- **w (write)**: The `w` permission allows users to create, delete, or rename files and subdirectories withing the directory. However, this alone doesn't give them the ability to enter the directory or access the files; they need execute, `x`, permission as well.

- **x (execute)**: The `x` permission is what allows users to **enter** the directory, meaning they can `cd` into it. Without this permission, users can not access the contents of the directory, even if they have read permission.   

These 3 permissions combine to control how users interact with directories:

- A directory with `r-x` permissions lets users list its contents and navigate into it, but they can not add or delete files

- A directory with `rwx` permissions allows users to navigate into it, list its contents and create or delete files inside.

- A directory with `rw-` permissions lets users add and delete files withing the direcotry but does not allow them to navigate into it or list its contents.

#### Modifying directory permissions

you can modify directory permissions just as you would with files. For example, to allow users to traverse a directory (enter it) but not modify its contents, you can add the execuse permission:

```bash
chmod +x <directory_name>
```

This command makes the directory accessible, allowing users to navigate into it using `cd`, but they won't be able to list the contents without the read permission (`r`).

#### Apllying changes recursively

If you want to modify permissions for a directory and all its subdirectories and files, you can use the `-R` option (recursive):

```bash
chmod -R 755 <directory_name>
```

This command will apply the `755` permissions to the directory and everything inside it. The `755` permission gives the owner full acess to the directory (read, write, execute) while giving others read and execute permissions but not write access.

::: {.callout-caution}
Avoid running `chmod -R 777` on directories especially system directories, web roots or shared project directories.
:::

Setting permissions to `777` gives **everyone** (including unauthorized users or processes) full control to read, write and execute files. This can expose sensitive data, allow tampering, or enable malicious code execution.

Instead of making everything universally accessible, consider which users actually need access and apply more specific permissions like `755` or `750` for directories and `644` or `640` for files.

# Managing ownership

Every file and directory on a Linux system has both an owner and an associated group. Ownership plays a key role in determining who can access or modify a file. especially in evironments where multiple users share the same system.

## Understanding ownership

Each file has 2 types of ownership:

1. **User (Owner)**: The person who created the file. By default, this user has permission to read, write or execute it.

2. **Group**: A group of users who may also have access to the file, depending on how group permissions are set.

As you have see, when you list fiels with `ls -l`, you will see both the user and group names:

```bash
drwxrwxr-x+ 4 luis.gomezl luis.gomezl 4096 Apr  4 11:36 marketing_report_project_1
```
In this example, the first `luis.gomezl` is the owner, and the second `luis.gomezl` is the group. You can change either (or both) using the `chown` command.

### Changing Ownership with `chown`

The `chown` command lets you change the user who owns a file or directory. Here is the basi syntax:

```bash
sudo chown <new_owner> <filename>
```

For example, to transfer ownership of `hello.txt` from `traw` to `john` you would run:

```bash
sudo chown john hello.txt
```

This command changes the owner of `hello.txt` to `john` while keeping the group ownership the same.

### Changing both user and group ownership

In some cases, you might need to change both the user and group ownership at the same time. With `chown`, this is straighforward. You specify both the new owner and the new group by separating them with a colon:

```bash
sudo chown new_owner:new_group filename
```

For example, if you want to change the owner of `hello.txt` to `john` and the group `dev`, you would run:

```bash
sudo chown john:dev hello.txt
```

This command changes the owner to `john` and the group to `dev`.

### Changing the ownership of multiple files

You can apply `chown` to multiple files at once. For example, to change the ownership of all `.txt` files in the current directory to `john` you can use:

```bash
sudo chown john *.txt
```

This command changes the owner of all fiels with a `.txt` extension to `john`.

In relation to the scope of the command it applies to the current directory but not for subdirectories and definitely not for the entire operating system.

If you are for example in `/home/luis.gomezl` this command would change your files, but it would leave the system files in `/etc` or `/usr/bin` completely untouched.

### Changing group ownership with `chgrp`

If you only need to change the group ownership of a file, you can use the `chgrp` command. The syntax is simple:

```bash 
sudo chgrp new_group filename
```

For example, to change the group of `hello.txt` to `admin`:

```bash
sudo chgrp admin hello.txt
```

This command changes only the group ownership, leaving the user ownership unchanged.

### Changing group ownership for multiple files

Like `chown`, you can also change the group ownership for multiple files in one go. To change the group for all `.log` files in a directory to `admin`, you could run:

```bash
sudo chgrp admin *.log
```

This applies the new group ownership to all files that match the `.log` extension in the current directory.

### Recursive ownership changes

Both `chown` and `chgrp` allow you to apply ownership changes to a directory and all of its contents (file and subdirectories) using `-R` (recursive) option. 

This is especially useful when you need to change the ownership of multiple files and subdirectories at one, rather than doing it one by one.

For example, to change the owner of an entrie directory and everything inside it to `john` and the group to `dev`, you would run:

```bash
sudo chown -R john:dev /backups/projects
```

Similarly you can use:

```bash
sudo chgrp -R sysadmin /backups
```

This command changes the group of the directory and all of tis contents to `admin`.

**Note**: The acronym of `chown` is **Ch**ange **Own**er