---
title: Advanced file access control
format:
  html: 
    toc: true
    number-sections: true
    code-fold: true
    embed-resources: true
---

Up to this point, you have worked with standard Linux permissions using the familiar `rwx` model. That is more then enough for most everyday tasks, but sometimes you need a bit more control.

In this chapter, you will learn SUID, SGID, the sticky bit, ACLs, and file attributes, and when to use each one.

# Beyond Standard Permissions?

Standard `rwx` permissions work well for most file and directory access needs. But sometimes, you need more than just read, write or execute, you need to control how a file behaves when it runs, or manage how users interact in share directories.

Linux gives you 3 special permission types that extend the basic model:

- Set User ID (SUID)
- Set Group ID (SGID)
- Sticky bit

These are known as special permissions, and they are used in very specific situations where standard permissions fall short.

Here is what they do:

- **SUID**: lets a program run with the permissions of a the file's owner
- **SGID**: makes sure files created in a shared directory inherit the directory group
- **Sticky bit**: prevents users from deleting each other's files in public directories like `/tmp`

These permissions are most commonly used in shared environments or for system tools that need elevated priviliges

## SUID (Set User ID)

The Set User ID (SUID) permission is used on executable files. When a file has the SUID bit set, it runds with the permissions of the file's owner, nt the user who launched it.

This is useful when a program needs elevated privileges to do its job, even if it is run by a regular user.

For example, take the `passwd` command, for example. It lets users change their own passwords, but the actual password data is stored in `/etc/shadow`, a file that only `root` can modifiy

It works because `/usr/bin/passwd` has the **SUID bit** set and is owned by `root`. That means when you run the command, it temporarily runs with `root` privileges, just long enough to make the requiered changes.

```bash
ls -l /usr/bin/passwd
```

Notice the `s` in the owner's permission field: `rws` instead of `rwx`. The lowercase `s` means the SUID bit is set and the file is executable.

```bash
-rwsr-xr-x. 1 root root 91424 Nov  3  2024 /usr/bin/passw
```

If the file was not executable you would see a capital `S` instead.

### Setting the SUID Bit

To set the SUID bit on a file you own (or have permission to modify), use:

```bash
chmod u+s filename
```
To remove it:

```bash
chmod u-s filename
```

You can also use numeric mode. The SUID bit has a value of 4 in the special permission slot, so:

```bash
chmod 4755 <filename>
```

This sets SUID along with `rwxr-xr-x` permissions

::: {.callout-caution}
SUID should be used carefully. A vulnerable SUID binary can be abused to gain elevated access.

Avoid setting SUID on scripts or on files in shared directories. Stick to well-audited system tools, and always double-check ownership and permissions before applying SUID manually.
:::

## SGID (Set Group ID)

The Set Group ID (SGID) permission behaves differently depending on whether it is applied to a file or a directory.

### SGID on executable files

When SGID is set on an executable file, the program runs with the **group** of the file, rather that the group of the user running it.

This is similar to SUID, but it affects group permissions instead of user permissions.

### SGID on Directories

This is where SGID is most useful. When applied to a directory, it ensures that **all files and subdirectories created inside the group ownership of the directory**, not the user's primary group.

That means if you have set up a shared directory for a team, everyone's files will stay under the same group so you don't need to manually adjust group wonership every time.

Let's say you team uses a shared directory at `srv/projects`, and it is owned by a group called `devteam`. You want anything created inside that directory (files, folders, scripts) to automatically blong to the `devteam` group, no matter who creates it.

To make that happen, you can set the SGID bit on the directory:

```bash
chmod g+s /srv/projects
```
After running that command, you will notice an `s` in place of the group's execute bit:

```bash
ls -ld /srv/projects
```

Like this:

```bash
drwxr-sr-x 2 user devteam 4096 May 21 14:12 projects
```

**Note**: If it is not installed in Oracle Linux 10 installed with `sudo dnf install acl` so you can check the hidden groups. In this way you can use **ACLs (Access Control Lists)**. In this way you can assign access levels to different groups and not only just one.

### Removing SGID

To remove the SGID bit from the directory:

```bash
chmod g-s /srv/projects
```

You can also set or remove SGID using numeric mode. The value for SGID is `2`, and it goes in the special permission slot (the first digit):

```bash
chmod 2755 /srv/projects
```

This sets SGID while keeping the rest of the permissions at `rwxr-xr-x`.

## The Sticky Bit

The sticky bit is used in directories to control file deletion in share spaces. When it is set, users can only delete or rename files they own, even if the directory is writable by everyone. 

### A closer look at `/tmp`

The `/tmp` directory is writable by all users and used to store temporary files. But you don't want users interfering with each other's files, so the sticky bit is set to prevent that.

You can check with:

```bash
ls -ld /tmp
```

```bash
drwxrwxrwt. 401 root root 45056 Apr 28 11:48 /tmp
```

The Sticky Bit permission is specify with a `t` in the "others" section

### Setting the Sticky Bit

To set in on a directory:

```bash
chmod +t dirname
```

To remove it:

```bash
chmod -t dirname
```

You cna also use numeric mode. The sticky bit has a value of `1` in the special permission slot:

```bash
chmod 1755 dirname
```

This sets the sticky bit while keeping regular permissions at `rwxr-xr-x`.

### When it is useful

The sticky bit is ideal for share directories where multiple users have write access, but should only be able to delete their own files. Besides `/tmp`, you will also see it used in group project spaces, shared classrooms or collaborative development enfironments.

## Additional notes

You can use `stat` command to see permissions in their numerical (octal) format (e.g., 755 or 644) rather than just the symbolic `-rwxr-xr-x`. 

```bash
stat marketing_r
```

```bash
  File: marketing_r
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 252,5	Inode: 62915522    Links: 11
Access: (0755/drwxr-xr-x)  Uid: ( 1002/luis.gomezl)   Gid: ( 1002/luis.gomezl)
Context: system_u:object_r:user_home_t:s0
Access: 2026-04-28 12:05:41.270566977 -0500
Modify: 2026-04-21 19:04:38.143964096 -0500
Change: 2026-04-21 19:04:38.143964096 -0500
 Birth: 2026-04-04 10:52:43.039342184 -0500
```
In this case for this folder (`marketing_r`) there is no special permission. If there is a permission we have:

- 4 = SUID
- 2 = SGID
- 1 Sticky bit

A common security check is to list files with SUID, SGID or sticky bits set and review whether each one is expected.

- To search for files with SUID, run:

```bash
find / -perm /4000
```

- To search for files with SGID, run:

```bash
find / -perm /2000
```

- To search for files that have either SUID or SGID, run:

```bash
find / -perm /6000
```

To find files with the sticky bit:

```bash
find / -perm /1000
```

# Access Control Lists (ACLs)

Standard Linux permissions using the `rwx` model work well in most situations, but they have a key limitation: you cna only assign permissions to **one user** (the owner) and **one group**. That might be enough for simple setups, but what if you need to give access to **multiple users** who are not in the same group?

That is where Access Control Lists (ACLs) come in.